### PR TITLE
First steps toward new logo

### PR DESCRIPTION
**Pull request by mattstauffer**
image

Chatted with @pascalpp thatt this is in progress and he's going to take over from here while i go to bed

### CODE REVIEW

**Comment by pascalpp** [comment]
@mattstauffer I'm just guessing here, but I'm not sure we should crop it. The amount of space around it is consistent, so the designer might have left that intentionally to ensure the logo gets that much space around it.

**Comment by pascalpp** [comment]
here's where I ended up:
image

- removed the Join Us header cuz that was a sort of stand-in logo, and now it would just fight with the StayWoke logo
- reverted back to Source Sans Pro. I don't think Roboto is a close enough match, and I think unless we can match it exactly it's better for the logo to have its own typeface that contrasts with the text content.
- moved '(Anti) Inaugration' down into the form, which lets the 'Pledge to RESIST.' header stand alone, which I think is more impactful.

Also updated the success page with the logo and a bit of color:

image

**Comment by mattstauffer** [comment]
@pascalpp Looks awesome! I agree w/r/t padding, I was just going to add it in CSS--because that makes the image more flexible for the future.

It looks like this is live, but this PR wasn't merged, so I don't know what the situation is here--I'll just let you run with this however is right based on what you've done with the code.

**Comment by pascalpp** [comment]
Yeah we have dockerhub building each branch so I just deployed this branch in case deray took another look, which I guess he did.

**Review by pascalpp — APPROVED** [review]

**Pull request merged**
